CREATE TABLE IF NOT EXISTS BRANDS (
  BRAND_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME varchar(100) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
  PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME varchar(100) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS PRICES (
  PRICE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  BRAND_ID BIGINT,
  START_DATE TIMESTAMP,
  END_DATE TIMESTAMP,
  PRICE_LIST INT,
  PRODUCT_ID BIGINT,
  PRIORITY INT,
  PRICE DOUBLE NOT NULL,
  CURR varchar(3) DEFAULT NULL,
  CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID),
  CONSTRAINT FK_BRAND_ID FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (BRAND_ID)
);